# Generated by Django 4.1.4 on 2023-02-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_bonus'),
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonus',
            new_name='Penalty',
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='receiver',
            new_name='profile',
        ),
    ]
