# Generated by Django 3.2.16 on 2023-02-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
