# Generated by Django 3.2.16 on 2023-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_deposit_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
